# SERVER CONFIGURATION
server.port=${SERVER_PORT}
server.servlet.context-path=${CONTEXT_PATH}
spring.application.name=gymnasion

# DATABASE CONFIGURATION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & HIBERNATE CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Disable SQL logging in terminal
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.highlight_sql=false

# LOGGING CONFIGURATION
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

# SECURITY CONFIGURATION (JWT)
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS}

# DEFAULT ADMIN CONFIGURATION
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
